apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dummy-container 
spec:
  params:
    - name: enriquesecret
      type: string
      default: "awsenriqueauth"
  steps:
    - name: dummy-container
      image: alpine
      command:
        - sh
      args:
        - '-c'
        - |
          sleep 100000
      env:
        - name: MY_USER
          valueFrom:
            secretKeyRef:
              name: $(params.enriquesecret)
              key: "AWS_ACCESS_KEY_ID"
