apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: signer-container 
spec:
  workspaces:
    - name: built-modules

  params:
    - name: enriquesecret
      type: string
      default: "awsenriqueauth"
    - name: kms-token
      type: string
      default: "kms-test-key"
  steps:
    - name: signer-container
      image: quay.io/ebelarte/aws-kms-pkcs11-signer:ubi8
      script: |
        #!/usr/bin/env bash
        ls -l /workspace/
        /bin/configure_pkcs.sh
        sleep 100000
      env:
        - name: AWS_ACCESS_KEY_ID 
          valueFrom:
            secretKeyRef:
              name: $(params.enriquesecret)
              key: "AWS_ACCESS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.enriquesecret)
              key: "AWS_SECRET_ACCESS_KEY"
        - name: AWS_KMS_TOKEN 
          valueFrom:
            secretKeyRef:
              name: $(params.kms-token)
              key: "AWS_KMS_TOKEN"

   
