apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: signer-container
spec:
  params:
    - name: enriquesecret
      type: string
      default: "awsenriqueauth"
    - name: kms-token
      type: string
      default: "kms-test-key"
    - name: IMAGE_URL
    - name: IMAGE_DIGEST
  workspaces:
    - name: buildmodules
      description: The workspace where compile modules will be stored
        #mountPath: /workspace/build-modules
  steps:
    - name: signer-container
      image: quay.io/ebelarte/aws-kms-pkcs11-signer:ubi8
      script: |
        #!/usr/bin/env bash
        ls -lR $SOURCE_PATH
        echo "Image URL:  $IMAGE_URL $(tasks.build-container.results.IMAGE_URL)"
          echo "Image Digest:  $IMAGE_DIGEST"
        #/bin/configure_pkcs.sh
        sleep 100000
      env:
        - name: SOURCE_PATH
          value: $(workspaces.buildmodules.path)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: $(params.enriquesecret)
              key: "AWS_ACCESS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.enriquesecret)
              key: "AWS_SECRET_ACCESS_KEY"
        - name: AWS_KMS_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.kms-token)
              key: "AWS_KMS_TOKEN"
