apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: use-secret
spec:
  inputs:
    resources:
      - name: secret-name
        type: string
        default: awsenriqueauth
  steps:
    - name: use-secret-value
      image: alpine
      command:
        - sh
      args:
        - '-c'
        - |
          echo "The string test is: $(cat /tekton/secrets/secret-name/AWS_ACCESS_KEY_ID)"

