apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: use-secret
spec:
  inputs:
    parameters:
      - name: secret-name
        type: string
        default: awsenriqueauth
  steps:
    - name: use-secret-value
      image: alpine
      script: |
        secretName="$params.secret-name"
        secretKey="AWS_ACCESS_KEY_ID"

        # Get the secret reference
        secret=$(kubectl get secret $secretName -o jsonpath='{.data.$secretKey}')

        # Get the value of the key
        secretValue=$(echo -n "$secret")

        # Print the value of the key
        echo "Using secret value: $secretValue"
