apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: use-secret
spec:
  inputs:
    resources:
      - name: awsenriqueauth 
        type: string
  steps:
    - name: use-secret-value
      image: alpine
      command:
        - sh
      args:
        - '-c'
        - |
          ls -l /tekton
          #echo "The string test is: $(cat /tekton/secrets/awsenriqueauth/AWS_ACCESS_KEY_ID)"

